project:
  type: default
  output-dir: _output

jupyter: python3

format:
  html:
    theme: cosmo
    embed-resources: true
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: Show code
    page-layout: full

execute:
  echo: false
  warning: false
  error: false
  cache: false
